"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
import {LayoutDashboard,Users,Gauge,BookOpen,FileText,WalletCards,Truck,BarChart3,Settings,ShieldCheck,Droplets,LogOut} from "lucide-react";
type Page="dashboard"|"customers"|"meters"|"readings"|"invoices"|"payments"|"tankers"|"reports"|"settings"|"users";
const nav=[["dashboard","الرئيسية",LayoutDashboard],["customers","المشتركون",Users],["meters","العدادات",Gauge],["readings","القراءات",BookOpen],["invoices","الفواتير",FileText],["payments","التحصيل",WalletCards],["tankers","أصحاب الوايتات",Truck],["reports","التقارير والإقفال",BarChart3],["settings","الإعدادات",Settings],["users","المستخدمون",ShieldCheck]] as const;
const money=(n:any)=>Number(n||0).toLocaleString("ar-YE")+" ريال";
export default function App(){const[s,setS]=useState<any>(null),[page,setPage]=useState<Page>("dashboard");useEffect(()=>{supabase.auth.getSession().then(({data})=>setS(data.session));const x=supabase.auth.onAuthStateChange((_e,ss)=>setS(ss));return()=>x.data.subscription.unsubscribe()},[]);if(!s)return <Login/>;return <div className="shell"><aside className="side"><div className="brand"><div className="logo"><Droplets/></div><div><b>نظام إدارة البئر</b><div className="muted" style={{color:"#d9f6ff"}}>بئر محمد أحمد مطير</div></div></div><div className="nav">{nav.map(([id,label,I])=>{const Icon=I;return <button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><Icon size={16}/> {label}</button>})}</div></aside><main className="main"><header className="top"><b>{nav.find(x=>x[0]===page)?.[1]}</b><div className="row"><span className="muted">{s.user.email}</span><button className="btn alt" onClick={()=>supabase.auth.signOut()}><LogOut size={15}/> خروج</button></div></header><div className="content">{page==="dashboard"&&<Dashboard/>}{page==="customers"&&<Customers/>}{page==="meters"&&<List table="bm_meters" title="العدادات"/>}{page==="readings"&&<Readings/>}{page==="invoices"&&<Invoices/>}{page==="payments"&&<List table="bm_payments" title="التحصيل"/>}{page==="tankers"&&<List table="bm_tanker_owners" title="أصحاب الوايتات"/>}{page==="reports"&&<Reports/>}{page==="settings"&&<List table="bm_settings" title="الإعدادات"/>}{page==="users"&&<List table="bm_profiles" title="المستخدمون والصلاحيات"/>}</div></main></div>}
function Login(){const[e,setE]=useState(""),[p,setP]=useState(""),[err,setErr]=useState("");return <div className="content" style={{minHeight:"100vh",display:"grid",placeItems:"center"}}><form className="card" style={{width:"min(430px,100%)"}} onSubmit={async x=>{x.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:e,password:p});if(error)setErr(error.message)}}><div className="logo" style={{margin:"0 auto"}}><Droplets/></div><h2 style={{textAlign:"center"}}>تسجيل الدخول</h2><input className="search" type="email" placeholder="البريد الإلكتروني" value={e} onChange={x=>setE(x.target.value)}/><input className="search" style={{marginTop:10}} type="password" placeholder="كلمة المرور" value={p} onChange={x=>setP(x.target.value)}/>{err&&<p className="danger">{err}</p>}<button className="btn" style={{width:"100%",marginTop:12}}>دخول</button></form></div>}
function Dashboard(){const[d,setD]=useState<any>({});useEffect(()=>{supabase.rpc("dashboard_summary").then(({data})=>setD(data||{}))},[]);return <><h2>لوحة التحكم</h2><p className="muted">البيانات من Supabase</p><div className="grid">{[["المشتركون",d.customers],["العدادات",d.meters],["الفواتير",d.invoices],["التحصيل",money(d.collections)],["المتأخرات",money(d.arrears)],["المصروفات",money(d.expenses)],["الصافي",money((d.collections||0)-(d.expenses||0))],["الفترة",d.period]].map(([k,v])=><div className="card stat" key={k}><span className="muted">{k}</span><b>{String(v??"—")}</b></div>)}</div></>}
function Customers(){const[r,setR]=useState<any[]>([]),[q,setQ]=useState("");useEffect(()=>{supabase.rpc("customer_search",{p_query:q}).then(({data})=>setR(data||[]))},[q]);return <><h2>المشتركون</h2><div className="card"><div className="row"><input className="search" placeholder="بحث بالاسم أو الهاتف أو الرقم" value={q} onChange={x=>setQ(x.target.value)}/></div><div className="tablewrap"><table className="table"><thead><tr><th>الرقم</th><th>الاسم</th><th>الهاتف</th><th>العداد</th><th>الرصيد</th><th>الحالة</th></tr></thead><tbody>{r.map(x=><tr key={x.id}><td>{x.customer_no}</td><td>{x.name}</td><td>{x.phone}</td><td>{x.meter_no}</td><td><b>{money(x.balance)}</b></td><td><span className="badge">{x.status}</span></td></tr>)}</tbody></table></div></div></>}
function List({table,title}:{table:string;title:string}){const[r,setR]=useState<any[]>([]);useEffect(()=>{supabase.from(table).select("*").limit(200).then(({data})=>setR(data||[]))},[table]);const cols=r.length?Object.keys(r[0]).slice(0,8):[];return <><h2>{title}</h2><div className="card tablewrap"><table className="table"><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{r.map((x,i)=><tr key={x.id||i}>{cols.map(c=><td key={c}>{typeof x[c]==="object"?JSON.stringify(x[c]):String(x[c]??"—")}</td>)}</tr>)}</tbody></table></div></>}
function Readings(){return <List table="bm_readings" title="القراءات"/>}
function Invoices(){const[r,setR]=useState<any[]>([]),[sel,setSel]=useState<any>(null);useEffect(()=>{supabase.from("bm_invoices").select("*,bm_customers(name,customer_no)").order("issue_date",{ascending:false}).limit(200).then(({data})=>setR(data||[]))},[]);return <><h2>الفواتير</h2><div className="card tablewrap"><table className="table"><thead><tr><th>الفاتورة</th><th>المشترك</th><th>الفترة</th><th>الاستهلاك</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th></th></tr></thead><tbody>{r.map(x=><tr key={x.id}><td>{x.invoice_no}</td><td>{x.bm_customers?.name}</td><td>{x.billing_period||x.issue_date}</td><td>{x.consumption}</td><td>{money(x.total_due)}</td><td>{money(x.amount_paid)}</td><td><b>{money(x.balance_due)}</b></td><td><button className="btn alt" onClick={()=>setSel(x)}>تفاصيل</button></td></tr>)}</tbody></table></div>{sel&&<div className="modalbg"><div className="modal"><div className="row" style={{justifyContent:"space-between"}}><h3>الفاتورة #{sel.invoice_no}</h3><button className="btn alt" onClick={()=>setSel(null)}>إغلاق</button></div><div className="grid"><div className="card stat"><span className="muted">الاستهلاك</span><b>{sel.consumption}</b></div><div className="card stat"><span className="muted">سعر الوحدة</span><b>{money(sel.unit_price)}</b></div><div className="card stat"><span className="muted">الرصيد السابق</span><b>{money(sel.previous_balance)}</b></div><div className="card stat"><span className="muted">المتبقي</span><b>{money(sel.balance_due)}</b></div></div><h3>تخصيصات الدفعات</h3><PaymentAlloc invoiceId={sel.id}/><button className="btn" style={{marginTop:14}} onClick={()=>window.print()}>طباعة / PDF</button></div></div>}</>}
function PaymentAlloc({invoiceId}:{invoiceId:string}){const[r,setR]=useState<any[]>([]);useEffect(()=>{supabase.from("bm_payment_allocations").select("amount,payment_id,bm_payments(payment_no,payment_date,payment_method,amount)").eq("invoice_id",invoiceId).then(({data})=>setR(data||[]))},[invoiceId]);return r.length?<div className="tablewrap"><table className="table"><thead><tr><th>الدفع</th><th>التاريخ</th><th>الطريقة</th><th>إجمالي الدفعة</th><th>المخصص</th></tr></thead><tbody>{r.map(x=><tr key={x.payment_id}><td>{x.bm_payments?.payment_no}</td><td>{x.bm_payments?.payment_date}</td><td>{x.bm_payments?.payment_method}</td><td>{money(x.bm_payments?.amount)}</td><td><b>{money(x.amount)}</b></td></tr>)}</tbody></table></div>:<p className="muted">لا توجد تخصيصات دفعات.</p>}
function Reports(){const[r,setR]=useState<any[]>([]);useEffect(()=>{supabase.from("bm_monthly_summary").select("*").order("starts_on",{ascending:false}).limit(24).then(({data})=>setR(data||[]))},[]);return <><h2>التقارير والإقفال</h2><div className="card tablewrap"><table className="table"><thead><tr><th>الفترة</th><th>الحالة</th><th>القراءات</th><th>الفواتير</th><th>المفوتر</th><th>التحصيل</th><th>الصافي</th></tr></thead><tbody>{r.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.status}</td><td>{x.readings_count}</td><td>{x.invoices_count}</td><td>{money(x.invoiced_amount)}</td><td>{money(x.collections_amount)}</td><td>{money(x.net_amount)}</td></tr>)}</tbody></table></div></>}
